import { Station } from '../types';

export const NCR_CENTER = { latitude: 28.6139, longitude: 77.2090, latitudeDelta: 0.75, longitudeDelta: 0.75 };

export const MOCK_STATIONS: Station[] = [
  {
    id:'ncr-gur-001', name:'Tata Power EV Hub - Cyber Hub', network:'Tata Power EZ Charge', networkShort:'TP',
    address:'DLF Cyber Hub, Phase 2', city:'Gurugram', coordinates:{latitude:28.4943,longitude:77.0897},
    reliabilityScore:9.2, reliabilityColor:'green', waitMinutes:4, waitText:'~4 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC Fast',powerKW:60,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'available',statusText:'Available'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:60, pricePerKWh:18, currency:'INR', operatingHours:'24 hours', amenities:['Parking','Food nearby','Mall nearby'], totalReviews:78, averageRating:4.6, isOpen:true, distance:0.4,
    reviews:[{id:'r1',userId:'u1',userName:'Priya S.',userInitials:'PS',rating:5,comment:'Reliable NCR charging point with good parking access.',tags:['Reliable','Fast'],tagTypes:['ok','ok'],createdAt:'2 days ago'}],
  },
  {
    id:'ncr-gur-002', name:'Statiq - MG Road Metro', network:'Statiq', networkShort:'ST',
    address:'MG Road Metro Station Parking', city:'Gurugram', coordinates:{latitude:28.4794,longitude:77.0808},
    reliabilityScore:8.4, reliabilityColor:'green', waitMinutes:8, waitText:'~8 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:30,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:7.4,status:'in_use',statusText:'In use · 18 min left'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:30, pricePerKWh:19, currency:'INR', operatingHours:'6 AM – 11 PM', amenities:['Metro','Parking','Food nearby'], totalReviews:41, averageRating:4.2, isOpen:true, distance:1.5,
    reviews:[{id:'r1',userId:'u2',userName:'Amit V.',userInitials:'AV',rating:4,comment:'Convenient location, sometimes busy during office hours.',tags:['Convenient','Busy'],tagTypes:['ok','warn'],createdAt:'5 days ago'}],
  },
  {
    id:'ncr-gur-003', name:'HPCL HP Charge - NH48', network:'HPCL', networkShort:'HP',
    address:'NH-48 Highway, Gurugram', city:'Gurugram', coordinates:{latitude:28.4527,longitude:77.0201},
    reliabilityScore:8.1, reliabilityColor:'green', waitMinutes:7, waitText:'~7 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:30,status:'available',statusText:'Available'},{id:'p2',type:'GBT',displayName:'GB/T DC',powerKW:30,status:'in_use',statusText:'In use · 9 min left'}],
    connectorTypes:['CCS2','GBT','Type2'], maxPowerKW:30, pricePerKWh:17, currency:'INR', operatingHours:'24 hours', amenities:['Petrol pump','Highway access'], totalReviews:37, averageRating:4.1, isOpen:true, distance:3.0,
    reviews:[{id:'r1',userId:'u6',userName:'Deepak M.',userInitials:'DM',rating:4,comment:'Good highway backup charger.',tags:['Highway','Backup'],tagTypes:['ok','ok'],createdAt:'4 days ago'}],
  },
  {
    id:'ncr-del-001', name:'Tata Power EV - Connaught Place', network:'Tata Power EZ Charge', networkShort:'TP',
    address:'Connaught Place Inner Circle Parking', city:'New Delhi', coordinates:{latitude:28.6315,longitude:77.2167},
    reliabilityScore:8.9, reliabilityColor:'green', waitMinutes:10, waitText:'~10 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC Fast',powerKW:60,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'in_use',statusText:'In use · 24 min left'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:60, pricePerKWh:20, currency:'INR', operatingHours:'24 hours', amenities:['Central Delhi','Parking','Food nearby'], totalReviews:92, averageRating:4.5, isOpen:true, distance:0.8,
    reviews:[{id:'r1',userId:'u7',userName:'Rohit B.',userInitials:'RB',rating:5,comment:'Strong location for Central Delhi charging.',tags:['Central','Reliable'],tagTypes:['ok','ok'],createdAt:'Yesterday'}],
  },
  {
    id:'ncr-del-002', name:'ChargeZone - Saket Select Citywalk', network:'ChargeZone', networkShort:'CZ',
    address:'Saket District Centre', city:'New Delhi', coordinates:{latitude:28.5284,longitude:77.2184},
    reliabilityScore:8.6, reliabilityColor:'green', waitMinutes:12, waitText:'~12 min', waitClass:'mid',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:50,status:'available',statusText:'Available'},{id:'p2',type:'CCS2',displayName:'CCS2 DC',powerKW:50,status:'offline',statusText:'Reported offline'}],
    connectorTypes:['CCS2'], maxPowerKW:50, pricePerKWh:21, currency:'INR', operatingHours:'10 AM – 11 PM', amenities:['Mall','Food court','Security'], totalReviews:55, averageRating:4.3, isOpen:true, distance:4.6,
    reviews:[{id:'r1',userId:'u8',userName:'Neha R.',userInitials:'NR',rating:4,comment:'Safe mall location, one port sometimes unavailable.',tags:['Safe','One port issue'],tagTypes:['ok','warn'],createdAt:'1 week ago'}],
  },
  {
    id:'ncr-del-003', name:'BSES EV Charging - Dwarka Sector 10', network:'BSES', networkShort:'BS',
    address:'Dwarka Sector 10 Market Parking', city:'New Delhi', coordinates:{latitude:28.5810,longitude:77.0573},
    reliabilityScore:7.8, reliabilityColor:'amber', waitMinutes:18, waitText:'~18 min', waitClass:'mid',
    ports:[{id:'p1',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:7.4,status:'in_use',statusText:'In use'}],
    connectorTypes:['Type2'], maxPowerKW:22, pricePerKWh:16, currency:'INR', operatingHours:'24 hours', amenities:['Market','Parking'], totalReviews:26, averageRating:3.9, isOpen:true, distance:7.2,
    reviews:[{id:'r1',userId:'u9',userName:'Simran K.',userInitials:'SK',rating:4,comment:'Good AC charging option in Dwarka.',tags:['AC charger'],tagTypes:['ok'],createdAt:'6 days ago'}],
  },
  {
    id:'ncr-noi-001', name:'Tata Power EV - DLF Mall of India', network:'Tata Power EZ Charge', networkShort:'TP',
    address:'DLF Mall of India, Sector 18', city:'Noida', coordinates:{latitude:28.5672,longitude:77.3210},
    reliabilityScore:9.0, reliabilityColor:'green', waitMinutes:6, waitText:'~6 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC Fast',powerKW:60,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'available',statusText:'Available'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:60, pricePerKWh:19, currency:'INR', operatingHours:'10 AM – 11 PM', amenities:['Mall','Food court','Security'], totalReviews:66, averageRating:4.6, isOpen:true, distance:5.1,
    reviews:[{id:'r1',userId:'u10',userName:'Karan J.',userInitials:'KJ',rating:5,comment:'Best Noida mall charger, clean and easy to find.',tags:['Noida','Reliable'],tagTypes:['ok','ok'],createdAt:'3 days ago'}],
  },
  {
    id:'ncr-noi-002', name:'Statiq - Sector 62 Noida', network:'Statiq', networkShort:'ST',
    address:'Sector 62 Commercial Belt', city:'Noida', coordinates:{latitude:28.6279,longitude:77.3649},
    reliabilityScore:7.5, reliabilityColor:'amber', waitMinutes:20, waitText:'~20 min', waitClass:'mid',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:30,status:'in_use',statusText:'In use · 30 min left'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:7.4,status:'available',statusText:'Available'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:30, pricePerKWh:18, currency:'INR', operatingHours:'24 hours', amenities:['Office area','Parking'], totalReviews:29, averageRating:3.8, isOpen:true, distance:8.4,
    reviews:[{id:'r1',userId:'u11',userName:'Ankit S.',userInitials:'AS',rating:3,comment:'Works but usually busy during weekdays.',tags:['Busy'],tagTypes:['warn'],createdAt:'1 week ago'}],
  },
  {
    id:'ncr-gha-001', name:'EESL Public Charger - Vaishali', network:'EESL', networkShort:'EE',
    address:'Vaishali Metro Station Parking', city:'Ghaziabad', coordinates:{latitude:28.6490,longitude:77.3391},
    reliabilityScore:7.2, reliabilityColor:'amber', waitMinutes:22, waitText:'~22 min', waitClass:'mid',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:25,status:'available',statusText:'Available'},{id:'p2',type:'GBT',displayName:'GB/T DC',powerKW:25,status:'offline',statusText:'Reported offline'}],
    connectorTypes:['CCS2','GBT'], maxPowerKW:25, pricePerKWh:15, currency:'INR', operatingHours:'6 AM – 10 PM', amenities:['Metro','Parking'], totalReviews:21, averageRating:3.6, isOpen:true, distance:11.2,
    reviews:[{id:'r1',userId:'u12',userName:'Manish T.',userInitials:'MT',rating:3,comment:'Useful for Ghaziabad, but check availability first.',tags:['Check first'],tagTypes:['warn'],createdAt:'2 weeks ago'}],
  },
  {
    id:'ncr-far-001', name:'ChargeZone - Faridabad Neelam Chowk', network:'ChargeZone', networkShort:'CZ',
    address:'Neelam Chowk Ajronda, Faridabad', city:'Faridabad', coordinates:{latitude:28.3974,longitude:77.3127},
    reliabilityScore:8.0, reliabilityColor:'green', waitMinutes:9, waitText:'~9 min', waitClass:'low',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC',powerKW:50,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'available',statusText:'Available'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:50, pricePerKWh:18, currency:'INR', operatingHours:'24 hours', amenities:['Highway access','Parking'], totalReviews:18, averageRating:4.0, isOpen:true, distance:14.0,
    reviews:[{id:'r1',userId:'u13',userName:'Vikas P.',userInitials:'VP',rating:4,comment:'Good Faridabad fast charger.',tags:['Fast'],tagTypes:['ok'],createdAt:'4 days ago'}],
  },
  {
    id:'ncr-gno-001', name:'Tata Power EV - Pari Chowk', network:'Tata Power EZ Charge', networkShort:'TP',
    address:'Pari Chowk, Greater Noida', city:'Greater Noida', coordinates:{latitude:28.4654,longitude:77.5087},
    reliabilityScore:8.3, reliabilityColor:'green', waitMinutes:11, waitText:'~11 min', waitClass:'mid',
    ports:[{id:'p1',type:'CCS2',displayName:'CCS2 DC Fast',powerKW:60,status:'available',statusText:'Available'},{id:'p2',type:'Type2',displayName:'Type 2 AC',powerKW:22,status:'in_use',statusText:'In use'}],
    connectorTypes:['CCS2','Type2'], maxPowerKW:60, pricePerKWh:19, currency:'INR', operatingHours:'24 hours', amenities:['Expressway access','Parking'], totalReviews:24, averageRating:4.1, isOpen:true, distance:18.3,
    reviews:[{id:'r1',userId:'u14',userName:'Arjun M.',userInitials:'AM',rating:4,comment:'Useful stop for Greater Noida and Yamuna Expressway side.',tags:['Expressway'],tagTypes:['ok'],createdAt:'1 week ago'}],
  },
];
